from aiogram.dispatcher.filters.state import StatesGroup, State

class AdminState(StatesGroup):
    kino_id = State()
    kino_name = State()
    kino_duration = State()
    kino_size = State()
    kino_year = State()
    kino_quality = State()
    kino_link = State()
    kino_verify = State()
    ads_verify = State()
    yesOrNo = State()
    languages = State()
    channels = State()
    newChannel = State()
    limitUsers = State()
    delChannel = State()
    updateChannel = State()
    update_username = State()
    miniads = State()
    updateminiad = State()
    newminiad = State()
    checkSub = State()